version: '3'

services:
    redis:
        image: redis
        ports:
            - 6379:6379
        networks: 
            - mynet
    app:
        build: 
            context: ./app
        depends_on: 
            - redis
        networks: 
            - mynet

networks: 
    mynet:
        driver: bridge